scalar UUID
scalar StreamState
scalar Timestamp
scalar URL
scalar SortingDirection

type StreamSession {
  app: UUID!,
  name: String!,
  url: URL!,
  state: StreamState!,
  timestamp: Timestamp!
}

type StreamSessionCursor {
  data: [ StreamSession ]!
  count: Int!
}

type Stream {
  name: String!
  app: UUID!
  key: UUID!
}

type StreamCursor {
  data: [ Stream ]!
  count: Int!
}

input NameInput {
  app: UUID!
  name: String!
}

input SortingInput {
  column: String
  direction: SortingDirection
}

input PaginationInput {
  search: String
  page: Int
  limit: Int
  sorting: SortingInput
}

type Query {
  streamSession(app: UUID!): StreamSession
  live: [ StreamSession ]!
  streams(pagination: PaginationInput): StreamCursor!
  stream(app: UUID!): Stream
  vods(app: UUID!, pagination: PaginationInput): StreamSessionCursor!
}

type Mutation {
  updateName(name: NameInput!): Stream
  regenerateKey(app: UUID!): Stream
  deleteStream(app: UUID!): Stream
}
