scalar UUID
scalar StreamState
scalar Timestamp
scalar URL
scalar SortingDirection
scalar JSON

type Session {
  uid: UUID!,
  app: UUID!,
  name: String!,
  url: URL!,
  state: StreamState!,
  timestamp: Timestamp!
}

type SessionPage {
  data: [ Session ]!
  count: Int!
}

type Stream {
  name: String!
  app: UUID!
  key: UUID!
  settings: JSON!
}

type StreamPage {
  data: [ Stream ]!
  count: Int!
}

input SortingInput {
  column: String
  direction: SortingDirection
}

input PaginationInput {
  search: String
  page: Int
  limit: Int
  sorting: SortingInput
}

type Query {
  streams(pagination: PaginationInput): StreamPage!
  stream(app: UUID!): Stream
  lives: [ Session ]!
  live(app: UUID!): Session
  vods(app: UUID!, pagination: PaginationInput): SessionPage!
  vod(uid: UUID!): Session!
}

type Mutation {
  addStream: Stream
  updateName(app: UUID!, name: String!): Stream
  regenerateKey(app: UUID!): Stream
  updateSettings(app: UUID!, settings: JSON!): Stream
  deleteStream(app: UUID!): Stream
}
