from node:24.11.0-alpine as builder

arg service
env service=${service}

copy package.json /source/package.json
copy package-lock.json /source/package-lock.json
copy ./workspaces /source/workspaces

run cd /source && npm install

run cd /source && npm --workspace=@pul.se/${service} run build

expose 80
cmd cd /source && npm --workspace=@pul.se/${service} run build && npm --workspace=@pul.se/${service} run develop

from node:24.11.0-alpine

arg service
env service=${service}

copy --from=builder /source/modules/@pul.se/${service}/dist /app

expose 80
cmd cd /app && node index.js


