services:
  ingress:
    image: 'caddy:2.11-alpine'
    restart: 'always'
    configs:
      - source: 'caddyfile'
        target: '/etc/caddy/Caddyfile'
    networks:
      - 'frontend'
    ports:
      - '80:80'
      - '443:443'
  web:
    image: 'pul.se/web:0.0.0'
    restart: 'always'
    build:
      args:
        SERVICE: 'web'
    networks:
      - 'frontend'
  auth:
    image: 'pul.se/auth:0.0.0'
    restart: 'always'
    build:
      args:
        SERVICE: 'auth'
    environment:
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'PULSE_HOSTNAME=${PULSE_HOSTNAME}'
      - 'GOOGLE_OAUTH_CLIENTID=${GOOGLE_OAUTH_CLIENTID}'
      - 'GOOGLE_OAUTH_CLIENTSECRET=${GOOGLE_OAUTH_CLIENTSECRET}'
      - 'JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}'
      - 'JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}'
    networks:
      - 'frontend'
      - 'backend'
  graphql:
    image: 'pul.se/graphql:0.0.0'
    restart: 'always'
    build:
      args:
        SERVICE: 'graphql'
    environment:
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'PULSE_CDN=${PULSE_CDN}'
      - 'JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}'
    networks:
      - 'frontend'
      - 'backend'
  buckets:
    image: 'pul.se/buckets:0.0.0'
    restart: 'always'
    build:
      args:
        SERVICE: 'buckets'
    environment:
      - 'STORAGE_ACCESS_KEY=${STORAGE_ACCESS_KEY}'
      - 'STORAGE_SECRET_KEY=${STORAGE_SECRET_KEY}'
    networks:
      - 'frontend'
      - 'backend'
  remuxer:
    image: 'pul.se/remuxer:0.0.0'
    restart: 'always'
    ports:
      - '1935:1935'
    build:
      context: './remuxer'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    environment:
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'STORAGE_ACCESS_KEY=${STORAGE_ACCESS_KEY}'
      - 'STORAGE_SECRET_KEY=${STORAGE_SECRET_KEY}'
    networks:
      - 'frontend'
      - 'backend'
  storage:
    image: 'rustfs/rustfs:1.0.0-alpha.91'
    restart: 'always'
    user: 'root'
    environment:
      - 'RUSTFS_ACCESS_KEY=${STORAGE_ACCESS_KEY}'
      - 'RUSTFS_SECRET_KEY=${STORAGE_SECRET_KEY}'
    volumes:
      - './data/rustfs/data:/data'
      - './data/rustfs/logs:/logs'
    networks:
      - 'backend'
  postgres:
    image: 'postgres:16-alpine'
    restart: 'always'
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    networks:
      - 'backend'

networks:
  frontend:
  backend:

configs:
  caddyfile:
    content: |
      ${PULSE_HOSTNAME} {
        reverse_proxy /graphql http://graphql
        reverse_proxy /buckets/* http://buckets
        reverse_proxy /auth/* http://auth

        reverse_proxy http://web
      }
