services:
  ingress:
    ports:
      - '8080:8080'
  web:
    build:
      target: 'builder'
    volumes:
      - './workspaces:/source/workspaces'
  auth:
    build:
      target: 'builder'
    volumes:
      - './workspaces:/source/workspaces'
  buckets:
    build:
      target: 'builder'
    volumes:
      - './workspaces:/source/workspaces'
  broadcast:
    build:
      target: 'builder'
    volumes:
      - './workspaces:/source/workspaces'
  graphql:
    build:
      target: 'builder'
    volumes:
      - './workspaces:/source/workspaces'
  remuxer:
    build:
      target: 'builder'
    volumes:
      - './remuxer:/source'
  storage:
    ports:
      - '9001:9001'
    environment:
      - 'RUSTFS_CONSOLE_ENABLE=true'
