services:
  auth:
    build:
      target: 'builder'
    volumes:
      - './workspaces:/source/workspaces'
  graphql:
    build:
      target: 'builder'
    volumes:
      - './workspaces:/source/workspaces'
  streams:
    build:
      target: 'builder'
    volumes:
      - './workspaces:/source/workspaces'
  web:
    build:
      target: 'builder'
    volumes:
      - './workspaces:/source/workspaces'
  remuxer:
    build:
      target: 'builder'
    volumes:
      - './remuxer:/source'
