[package]
name = 'remuxer'
version = '0.0.0'
edition = '2024'

[dependencies]
tokio = { version = "1.48.0", features = [ "full" ] }
rtmp-rs = "0.5.0"
tokio-postgres = { version = "0.7.17", features = ["with-uuid-1"] }
uuid = "1.11"
gstreamer = "0.25.1"
gstreamer-app = "0.25.0"
aws-sdk-s3 = "1.129.0"
aws-config = "1.8.15"
